# Generated by Django 4.1.9 on 2023-05-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("moeda", models.CharField(max_length=50)),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
